### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by 1over137** [ffreemt/scrape-glosbe-dict#1]
Hello,
I am the author of [VocabSieve](https://github.com/FreeLanguageTools/vocabsieve), a tool for creating Anki cards while reading foreign language texts to gain vocabulary.

Recently, one of the online dictionary sources (https://github.com/meetDeveloper/freeDictionaryAPI) offered in my tool switched to English only (no more definitions in other languages), so I had to remove it since it became a frontend of wiktionary, which I already had. It would be great if I can add yet another dictionary source by reusing some of the code here!

By the way, is this tool able to provide detailed definitions, rather than only a translation?

**Comment by ffreemt** [comment]
Hello.

Scraping glosbe is not too difficult, at least not for the translation part. The problem is their "Human test": after about 400 visits per day per IP address, a "Human test" will pop up that requires human intervention.

This tool just fetches translations for a certain word (e.g. make for English to German) from https://glosbe.com/en/de/make.  https://glosbe.com also provides other information such as detailed definitions and example sentences.
